SELECT
SUM("TREAT"."AMOUNTJP_DISC") AS "TREAT_AMOUNTJP_DISC"
FROM "TREAT"
LEFT JOIN "DIAGNOSIS" ON "TREAT"."DGCODE" = "DIAGNOSIS"."DGCODE"
--WHERE "TREAT"."PCODE" IN ('100003230,')
AND "DIAGNOSIS"."DGNAME" IN ('Общий медецинский осмотр')
 --AND "TREAT"."TREATDATE" < ? AND "TREAT"."TREATDATE" > ?
;